version: "3.9"

services:

  training-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - xumak-network

volumes:
  db:
    driver: local

networks:
  xumak-network: